Added starter for web project.
vstund/TictacToe pull request #13
Opened 2021-11-07 20:49 UTC by ZZE0001

2021-11-08 07:44 UTC, ZZE0001 commented
Jautājums - kā var no kontroliera rediģēt board objektu (HttpPut)? Vai tas būs tas pats objekts kas konsoles projektā?

2021-11-08 09:31 UTC, artisvilcins requested changes
Vēlams savest kārtībā .gitignore failu arī, lai nerādītos arī šeit visas šīs papildus izmaiņas no vizuālās studijas

2021-11-08 09:40 UTC, artisvilcins commented
P.s. Vēlams palasīt par websocket un SignalR. Tas noteikti ir ārpus šī PR skopa, bet ja projektu paspēsiet tik tālu, ka gribās, lai viens spēlētājs izvēlās laukumu, kur liks savu simbola un otram uzreiz parādās viņā izvēle neko nedarot pa skaisto, tad vajadzēs web soketus.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-6.0

2021-11-08 11:14 UTC, ZZE0001 commented
> P.s. Vēlams palasīt par websocket un SignalR. Tas noteikti ir ārpus šī PR skopa, bet ja projektu paspēsiet tik tālu, ka gribās, lai viens spēlētājs izvēlās laukumu, kur liks savu simbola un otram uzreiz parādās viņā izvēle neko nedarot pa skaisto, tad vajadzēs web soketus.
> 
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-6.0

Palasīšu, paldies!

2021-11-08 11:24 UTC, artisvilcins commented
Es nezinu neesmu sīkāk pētījis, kā redzu, ka šajā PR ir izmainīti 401 faili, no kuriem liela daļa ir tamlīdzīgi

2021-11-08 13:41 UTC, ZZE0001 commented
> Sākotnēji šo klasi piereģistrējot kā Si9ngleton,

Vai pagaidām varētu izmantot IMemoryCache kur uzglabāt datus vienā vietā? Gan priekš web, gan konsoles. Vēlāk protams datubāzē, ja paspēsim.

2021-11-08 14:32 UTC, artisvilcins commented
Ja vēlies tad varat jā pieglabāt iekš MemoryCache, bet es tomēr ieteiktu izmantot entityFrameworkCore kopā ar in memory datubāzi.

Šādi izdarot būs daudz vieglāk pēc tam pārslēgties uz reālu datubāzi, jo viss, kas būs jāizdara būs jānomaina, kur tiek glabāti dati. Tā ir entityframeworku maģija :) 

Domāju, ka viņu uzstādīt strādājošu izmantojot iun memory datubāzi nevajedzētu aizņemt pārāk daudz laiku galvenais tur 
datu modeļus tikai pareizi sataisīt.

2021-11-10 15:19 UTC, ZZE0001 commented
@artisvilcins Lūdzu var palīdzēt ar pēdējo kommitu? Pievienoju In Memory datubāzi. Pie POST kontroliera gribu modificēt BoardContext un ievietot jauno lauka vērtību. POST kontrolieris nostrādā, bet pēc tam izsaucot GET kontrolieri konteksts nav izmainījies.

Vēlamais rezultāts:
GET [1, 2, 3, 4, 5, 6, 7, 8, 9]
POST [X, ,2, 3, 4, 5, 6, 7 ,8, 9]
**GET** [**X,** 2, 3, 4, 5, 6, 7, 8, 9]

Šobrīd esošais rezultāts:
GET [1, 2, 3, 4, 5, 6, 7, 8, 9]
POST [X, ,2, 3, 4, 5, 6, 7 ,8, 9]
**GET** [**1,** 2, 3, 4, 5, 6, 7, 8, 9]

2021-11-10 18:33 UTC, artisvilcins requested changes

2021-11-10 18:33 UTC, artisvilcins commented on TictacToe/TictacToe.Web/Controllers/BoardController.cs
> +            _context.Entry(tt).State = EntityState.Modified;
Šī vieta ir nedaudz jocīga šādi parasti nedara. 

 _context.BoardContext.Update(tt);
await _context.SaveChangesAsync();

2021-11-11 08:16 UTC, artisvilcins commented
Tagad sāka strādāt kā vajag?

2021-11-11 08:17 UTC, ZZE0001 commented
Izmainīju, bet tik un tā pēc POST izsaukšanas GET izmaiņas neparādās. Pārbaudīju ar atkļūdotāju (debuger) un izmaiņas kontekstā objektā pirms sagalbāšanas it kā tiek pievienotas. Kur vēl varētu būt problēma?

2021-11-11 11:53 UTC, ZZE0001 commented
Laikam nav kaut kas ar konteksta inicializāciju. Atkļūdotājā, katru reizi pirms GET metodes Board objekts tiek izveidots par jaunu. Šobrīd skatos, kā risināt.

2021-11-12 16:11 UTC, artisvilcins approved these changes

2021-11-16 12:30 UTC, merged