Added exception
vstund/TictacToe pull request #14
Opened 2021-11-09 19:49 UTC by vstund

2021-11-09 20:34 UTC, artisvilcins requested changes
ļoti labi, tikai tādas mazas divas smukumlietas, ko pielabot

2021-11-09 20:34 UTC, artisvilcins commented on TictacToe/TictacToe/HumanPlayer.cs
> +            catch (FormatException formatException)
catch (FormatException formatException)
 to

            catch (FormatException)

2021-11-09 20:34 UTC, artisvilcins commented on TictacToe/TictacToe/HumanPlayer.cs
> +                Console.WriteLine($"{error.Message}");
Console.WriteLine($"{error.Message}");
to
                Console.WriteLine(error.Message);

2021-11-12 14:09 UTC, ZZE0001 commented
@vstund Čau! Lūdzu pielabosi Arta ieteikumus augstāk, lai var samērdžot ar main zaru pirms nākošnedēļas prezentācijas.

2021-11-13 11:17 UTC, merged