Added IPlayer interface.
vstund/TictacToe pull request #8
Opened 2021-10-26 20:20 UTC by ZZE0001

Added IPlayer interface and game menu.

2021-10-29 20:24 UTC, artisvilcins requested changes

2021-10-29 20:24 UTC, artisvilcins commented on TictacToe/TictacToe/IPlayer.cs
> +        public Signs Sign { get; set; }
Zīmi un vārdu tiešām vajadzīgs mainīt pēc spēlētāja izveidošanas?

2021-10-29 20:24 UTC, artisvilcins commented on TictacToe/TictacToe/Menu.cs
> +            return new HumanPlayer(player1Input, Signs.X);
Ja spēlēs 2 cilvēka spēlētāji tad abi spēlēs ar zimi x

2021-10-29 20:24 UTC, artisvilcins commented on TictacToe/TictacToe/Menu.cs
> +            return new ComputerPlayer(Signs.O);
Ja spēlēs 2 datora spēlētāji tad abi spēlēs ar zimi O

2021-10-29 20:24 UTC, artisvilcins commented on TictacToe/TictacToe/Menu.cs
> +            InitiateGame();
Visam nav jānotiek konstruktorā. Šī klase varētu būt spēles uzsākšanas palīgs vai kas tāds. Nav īsti pareizi, ka tik daudz loģikas tiek izpildītas klases izveidošanas brīdī. Klases izveidošanai ir jābūt ātrai un vienkāršai.

Idejiski ierobežojums no manas puses. Klases izveides laikā nedrīkst būt neviens Console.WriteLine

2021-10-29 20:24 UTC, artisvilcins commented on TictacToe/TictacToe/IPlayer.cs
> +        int MakeAMove();
Spēlētājam vajedzētu saņemt spēles laukumu pie gājiena taisīšanas, lai spēlētājs varētu "izdomāt" nākošo gājienu.

Ja paskatāmies vienu soli uz priekšu, tad kā datora spēlētājs spēs izdomāt kalt par kripatu gudrāku loģiku gājiena veikšanai, ja viņš nemaz nezin, kāds ir spēles laukums.

2021-11-02 11:54 UTC, ZZE0001 commented on TictacToe/TictacToe/IPlayer.cs
> +        public Signs Sign { get; set; }
Interfeisā neļauj izmantot konstruktorus. Kā citādi mainīt līdz ar spēlētāju izveidošanu?

2021-11-02 11:55 UTC, ZZE0001 commented on TictacToe/TictacToe/Menu.cs
> +            return new HumanPlayer(player1Input, Signs.X);
Darīts.

2021-11-02 11:55 UTC, ZZE0001 commented on TictacToe/TictacToe/Menu.cs
> +            return new ComputerPlayer(Signs.O);
Izmainīs.

2021-11-02 11:55 UTC, ZZE0001 commented on TictacToe/TictacToe/Menu.cs
> +            InitiateGame();
Izmainīts.

2021-11-02 11:55 UTC, ZZE0001 commented on TictacToe/TictacToe/IPlayer.cs
> +        int MakeAMove();
Izmainīts.

2021-11-02 13:09 UTC, artisvilcins commented on TictacToe/TictacToe/IPlayer.cs
> +        public Signs Sign { get; set; }
Padot klases kontruktorā. Klasē taču var izveidot konstruktoru ar parametriem :)

2021-11-02 13:13 UTC, artisvilcins approved these changes
Kas ir ir ok.

Papildus prasās uztaisīt pārbaudi, ka gan dators, gan cilvēka spēlētājs nevar mainīt viens otra jau aizņemtos laukumus. Šobrīd neredzu pārbaudi, ka viens spēlētājs nedrīkst pārrakstīt cita spēlētāja ievades.

2021-11-02 15:20 UTC, ZZE0001 commented
@artisvilcins Par pēdējo komentāru. Board klasē ir metode IsEmptyFieldChecker(), kura neļauj pārrakstīt jau aizņemots laukus.

2021-11-02 15:21 UTC, merged